packages:
    - name: api
      environment:
        MONGODB_URI: "${MONGODB_URI}"
        TEXTMEBOT_API_KEY: "${TEXTMEBOT_API_KEY}"
      functions:
        - name: export
          runtime: python:default
          web: true
        - name: soap
          runtime: python:default
          web: true
        - name: reservasi
          runtime: python:default
          web: true
        - name: clear
          runtime: python:default
          web: true